server:
  port: 8082
spring:
  application:
    name: eureka-discoveryclient
eureka:
  client:
    registerWithEureka: true 
    fetchRegistry: true
    preferSameZoneEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  server:
    enable-self-preservation: false